/node_kamera:
  ros__parameters:
    device_utama: 0
    device_bawah: ""
    device_samping: ""
    fps_utama: 30
    fps_bawah: 10
    fps_samping: 10
    frame_width: 640
    frame_height: 480

/node_deteksi:
  ros__parameters:
    model_path: "/home/aji/robot_ws/finallll_detek.onnx"
    conf_threshold: 0.7
    mission_conf_threshold: 0.6
    required_frames: 5
    horizon_ratio: 0.33
    inference_interval_ms: 100

/node_lidar:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"
    baudrate: 460800
    num_sectors: 4
    obstacle_distance: 0.5
    publish_scan: true
    frame_id: "laser_frame"
    csv_path: "/tmp/lidar_data.csv"
    csv_raw: false
    las_output: true
    las_dir: "/tmp/lidar_las"

/node_navigasi:
  ros__parameters:
    waypoint_lat: -7.052600
    waypoint_lon: 110.434800
    cruise_speed: 0.5
    approach_speed: 0.35
    visual_p_gain: 0.002
    visual_i_gain: 0.0001
    visual_d_gain: 0.0005
    lpf_alpha: 0.3
    gps_p_gain: 0.05
    max_yaw_rate: 0.5
    obstacle_stop_dist: 0.4
    obstacle_avoid_speed: 0.3
    fusion_dist_min: 0.3
    fusion_dist_max: 3.0
    fusion_speed_min: 0.15
    fusion_speed_max: 0.6

/node_motor:
  ros__parameters:
    serial_port: "/dev/ttyACM0"
    baudrate: 115200
    protocol: "mavlink"
    max_linear: 0.5
    max_angular: 0.8
    auto_control: true

/node_misi:
  ros__parameters:
    firebase_key_path: "/home/aji/robot_ws/firebase-key.json"
    firebase_url: "https://asvmonitoringweb-default-rtdb.asia-southeast1.firebasedatabase.app/"
    firebase_ref: "/kapal/tim-asv-01"
    cloudinary_cloud: "ds2j86wki"
    cloudinary_key: "563889432822331"
    cloudinary_secret: "Nr7nKUADbjW3w2E-SwCt1EBfC6E"
    cloudinary_folder: "asv_lomba"
    capture_cooldown: 5.0
