#!/bin/bash
source ~/robot_ws/install/setup.bash
echo "=== ROS2 Nodes ==="
ros2 node list 2>/dev/null || echo "(no nodes)"
echo ""
echo "=== Topics ==="
ros2 topic list 2>/dev/null || echo "(no topics)"
echo ""
echo "=== /asv/tracking ==="
timeout 2 ros2 topic echo /asv/tracking 2>/dev/null || echo "(not published)"
echo ""
echo "=== /asv/cmd_vel ==="
timeout 2 ros2 topic echo /asv/cmd_vel 2>/dev/null || echo "(not published)"
echo ""
echo "=== /asv/deteksi ==="
timeout 2 ros2 topic echo /asv/deteksi --once 2>/dev/null || echo "(not published)"
echo ""
echo "=== CSV log lines ==="
wc -l /tmp/navigasi_log.csv 2>/dev/null || echo "(no log)"
